import { describe, expect, test } from "bun:test";
import nodePath from "node:path";
import { memfs } from "memfs";
import {
  generateEntries,
  generateImports,
  generateRoutes,
} from "../entries-generation";
import { type RequiredFSFeatures, findRoutes } from "../find-routes";

function makeFS(tree: Parameters<typeof memfs>[0]): RequiredFSFeatures {
  let memoryFs = memfs(tree, "./");
  return memoryFs.fs as RequiredFSFeatures;
}

let fs = makeFS({
  src: {
    app: {
      "@root.tsx": "export default function Root() {}",
      "@layout.tsx": "export default function Layout() {}",
      "@not-found.tsx": "export default function NotFound() {}",
      //   "@error.tsx": "export default function Error() {}",
      "page.tsx": "export default function Homepage() {}",
      dashboard: {
        "@layout.tsx": "export default function Layout() {}",
        "page.tsx": "export default function Dashboard() {}",
      },
      api: {
        "route.ts": "export default function apiRoute() {}",
      },
      "[id]": {
        "page.tsx": "export default function DynamicSegment({id}) {}",
      },
      "[...slug]": {
        "page.tsx": "export default function CatchAllSegment({slug}) {}",
      },
    },
  },
});

let routes = findRoutes("./src/app/", {
  fs,
});

describe("generateImports", () => {
  test("should generate imports", () => {
    expect(
      generateImports(
        {
          appPath: "./src/app",
          routeDefinitions: routes,
        },
        {
          nodePath,
        },
      ),
    ).toEqual([
      'import layout0 from "./app/@layout";',
      'import notFound1 from "./app/@not-found";',
      'import root2 from "./app/@root";',
      'import page3 from "./app/[...slug]/page";',
      'import page4 from "./app/[id]/page";',
      'import route5 from "./app/api/route";',
      'import layout6 from "./app/dashboard/@layout";',
      'import page7 from "./app/dashboard/page";',
      'import page8 from "./app/page";',
    ]);
  });
});

describe("generateRoutes", () => {
  test("should generate routes", () => {
    expect(generateRoutes(routes)).toEqual([
      'createLayout({\n  render: "dynamic",\n  path: "/",\n  component: layout0,\n}),',
      "// @TODO - unsupported for now",
      'createRoot({\n  render: "dynamic",\n  component: root2,\n}),',
      'createPage({\n  render: "dynamic",\n  path: "/[...slug]",\n  component: page3,\n}),',
      'createPage({\n  render: "dynamic",\n  path: "/[id]",\n  component: page4,\n}),',
      'createApi({\n  render: "dynamic",\n  path: "/api",\n  handlers: {\n    GET: route5,\n    POST: route5,\n    PUT: route5,\n    DELETE: route5,\n    PATCH: route5,\n    OPTIONS: route5,\n    HEAD: route5,\n  },\n}),',
      'createLayout({\n  render: "dynamic",\n  path: "/dashboard",\n  component: layout6,\n}),',
      'createPage({\n  render: "dynamic",\n  path: "/dashboard",\n  component: page7,\n}),',
      'createPage({\n  render: "dynamic",\n  path: "/",\n  component: page8,\n}),',
    ]);
  });
});

describe("generateEntries", () => {
  test("should generate entries", () => {
    expect(
      generateEntries(
        {
          appPath: "./src/app",
          routeDefinitions: routes,
        },
        { nodePath },
      ),
    ).toEqual(
      `/* this file is automatically generated by garbanzo */
/* DO NOT MANUALLY EDIT THIS FILE */

import { createPages } from "waku";
import type { PathsForPages } from "waku/router";

import layout0 from "./app/@layout";
import notFound1 from "./app/@not-found";
import root2 from "./app/@root";
import page3 from "./app/[...slug]/page";
import page4 from "./app/[id]/page";
import route5 from "./app/api/route";
import layout6 from "./app/dashboard/@layout";
import page7 from "./app/dashboard/page";
import page8 from "./app/page";

let pages = createPages(async ({ createPage, createLayout, createRoot, createApi }) => [
createLayout({
  render: "dynamic",
  path: "/",
  component: layout0,
}),
// @TODO - unsupported for now
createRoot({
  render: "dynamic",
  component: root2,
}),
createPage({
  render: "dynamic",
  path: "/[...slug]",
  component: page3,
}),
createPage({
  render: "dynamic",
  path: "/[id]",
  component: page4,
}),
createApi({
  render: "dynamic",
  path: "/api",
  handlers: {
    GET: route5,
    POST: route5,
    PUT: route5,
    DELETE: route5,
    PATCH: route5,
    OPTIONS: route5,
    HEAD: route5,
  },
}),
createLayout({
  render: "dynamic",
  path: "/dashboard",
  component: layout6,
}),
createPage({
  render: "dynamic",
  path: "/dashboard",
  component: page7,
}),
createPage({
  render: "dynamic",
  path: "/",
  component: page8,
}),
]);

declare module "waku/router" {
  interface RouteConfig {
    paths: PathsForPages<typeof pages>;
  }
  interface CreatePagesConfig {
    pages: typeof pages;
  }
}

export default pages;`,
    );
  });
});
